apiVersion: v1
kind: Pod
metadata:
  name: narwhal-runner
  namespace: kt-local-eth-testnet
spec:
  restartPolicy: Never
  containers:
  - name: narwhal-runner
    image: ubuntu:22.04
    command: ["sleep", "infinity"]
    resources:
      requests:
        cpu: "4"
        memory: "8Gi"
      limits:
        cpu: "8"
        memory: "16Gi"
